name: dbt CI

on:
  pull_request:
    branches: [ staging, main ]
  push:
    branches: [ staging, main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install dbt-core dbt-postgres  # Replace with your adapter
          pip install sqlfluff sqlfluff-templater-dbt
          dbt deps
      
      - name: Run dbt lint
        run: sqlfluff lint models/
      
      - name: Run dbt compile 
        run: dbt compile
      
      - name: Run dbt test
        run: dbt test